# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore synergy.sln

      - name: Build solution
        run: msbuild synergy.sln /p:Configuration=Release

      - name: Locate VSTest.Console
        id: locate-vstest
        run: |
          echo "::set-output name=vstest-path::$(vswhere -latest -requires Microsoft.Component.MSBuild -find **/vstest.console.exe)"

      - name: Run unit tests
        run: |
          ${{ steps.locate-vstest.outputs.vstest-path }} Tests/bin/Release/Tests.dll
